### PR TITLE
Update chapter_template.php

### PR DESCRIPTION
**Pull request by yesszus**
Changes to development.

### CODE REVIEW

**Comment by Jimmi08** [comment]
@yesszus  Thanks. This will help a lot of.  I will use your code in future, but I can't apply LAN Strings in theme.php or templates before it's finished, it's harder to make changes then.  I used deliberately core shortcode for sitedisclaimer.

@CaMer0n You should consider the change in core sc_disclaimer() shortcode.  It's rewritten regularly in theme as I see.

And he added e107::lan('theme', 'admin',true);   to theme_config.php and now it's there twice. What is correct way? Outside class or in _construct() ?



https://github.com/yesszus/agency/blob/8dd81e191cc8e9b59e179611a0f579f2246c50d4/theme_config.php

**Comment by yesszus** [comment]
@Jimmi08  see this currently changes in landingzero theme: https://github.com/e107inc/e107/blob/master/e107_themes/landingzero/theme_config.php

**Comment by Jimmi08** [comment]
@yesszus I noticed this and I added it in this theme (in construct) and it worked. So I am surprised that it needs to be added again.
By the way, not all demo data are in install.xml, but you can upload them manually via Database Tools Thanks for helping again. I've got stuck with user avatars, so I can apply your changes... 
demo is here http://agency.e107.sk/

**Comment by yesszus** [comment]
e107 hun

**Comment by Jimmi08** [comment]
Why this change?  At first, there is still not working form from html template so any changes are useless.  And these texts are inside input fields, you are breaking layout with them - columns should be the same height.   
It's bootstrap 4 I haven't get to forms yet.  And there is ajax too...

**Comment by Jimmi08** [comment]
@yesszus 
from where are these strings?
define("LAN_AG_THEME_03", "We love feedback. Fill out the form below and we\'ll get back to you as soon as possible.");
define("LAN_AG_THEME_04", "Stay Posted");
I can't find them

**Comment by yesszus** [comment]
2 strigs in Landig zero theme

**Comment by yesszus** [comment]
Only to development.

**Comment by Jimmi08** [comment]
@yesszus You now can check lang strings.  Many thanks again.

**Pull request closed without merging**
